#version: '3.9'

services:
  mysql:
    container_name: mysql_erp
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: classicmodels
      MYSQL_USER: erp_user
      MYSQL_PASSWORD: erppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dw_network
    restart: always

  postgres:
    container_name: postgres_dw
    image: postgres:13
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: dwpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dw_network
    restart: always

  metabase:
    container_name: metabase_viz
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: dev_dw
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: dwpassword
      MB_DB_HOST: postgres_dw
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - postgres
    networks:
      - dw_network
    restart: always

  streamlit:
    container_name: streamlit_app
    image: python:3.9-slim
    volumes:
      - ./app:/app
    ports:
      - "8501:8501"
    command: ["sh", "-c", "pip install streamlit pandas numpy && streamlit run /app/app.py"]
    depends_on:
      - postgres
    networks:
      - dw_network
    restart: always


networks:
  dw_network:
    driver: bridge

volumes:
  mysql_data:
  postgres_data:
  metabase_data: